apiVersion: apps/v1
kind: Deployment
metadata:
  name: polnilnice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polnilnice
  template:
    metadata:
      labels:
        app: polnilnice
    spec:
      containers:
        - image: kkklemennn/polnilnice:2022-11-24-18-56-15
          name: polnilnice
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://lucky.db.elephantsql.com/aepmvvhs
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: aepmvvhs
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: IP7DNKFR12gyWpjYIl2kbf3XVznjniou
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: polnilnice
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: polnilnice